defaults:
  - mettagrid
  - _self_

game:
  num_agents: 4
  max_steps: 250
  map_builder: maze
  groups:
    mazer:
      id: 0
      sprite: 10
      props: {}

  objects:
    altar:
      cooldown: 250

  actions:
    move: {}
    attack: {}
