
defaults:
  - mettagrid

game:
  num_agents: 24

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${div:${..num_agents},6}
    border_width: 6

    room:
      _target_: mettagrid.config.room.random.Random
      width: ${if:${eq:${..sampling},0},25,${uniform:10,100}}
      height: ${if:${eq:${..sampling},0},25,${uniform:10,100}}
      border_width: 0

      agents: 6

      objects:
        mine: ${if:${eq:${..sampling},0},10,${uniform:1,20}}
        generator: ${if:${eq:${..sampling},0},2,${uniform:1,10}}
        altar: ${if:${eq:${..sampling},0},1,${uniform:1,5}}
        armory: ${if:${eq:${..sampling},0},1,${uniform:1,5}}
        lasery: ${if:${eq:${..sampling},0},1,${uniform:1,5}}
        lab: ${if:${eq:${..sampling},0},1,${uniform:1,5}}
        factory: ${if:${eq:${..sampling},0},1,${uniform:1,5}}
        temple: ${if:${eq:${..sampling},0},1,${uniform:1,5}}

        block: ${if:${eq:${..sampling},0},20,${uniform:5,50}}
        wall: ${if:${eq:${..sampling},0},20,${uniform:5,50}}
