
defaults:
  - mettagrid

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${div:${..num_agents},5}
    border_width: 6

    room:
      _target_: mettagrid.config.room.random.Random
      width: ${if:${eq:${..sampling},0},25,${uniform:10,100}}
      height: ${if:${eq:${..sampling},0},25,${uniform:10,100}}
      border_width: 0

      agents:
        prey: 4
        predator: 1

      objects:
        altar: ${if:${eq:${..sampling},0},1,${uniform:1,5}}
        converter: ${if:${eq:${..sampling},0},5,${uniform:1,15}}
        generator: ${if:${eq:${..sampling},0},15,${uniform:1,50}}
        wall: ${if:${eq:${..sampling},0},40,${uniform:10,100}}


